language: java
jdk:
  - openjdk8
services:
  - docker
matrix:
  fast_finish: true

env:
  global:
    # DOCKER_USER
    - secure: "BDUJ9S0PYG9Osn/3WU/ZX2VmfhlX47w26Nb7R0ZLPqHi9aSOfdp0uUZg+QES1jptYvdp/vt1MVtpRYnyMwJMbvUaQKEgdihKuD3KROoYu5lEu/pSjqB1bcDXlXGGzAaNQi1uTFIhU0NgMshuSjjMNyf2U6xwqus/A8rUkUOcLg8SPfGGUithoEa80SGaH9KrH9ksHuqgFRrLjXAdGUoHTN5Szm71GJ8hot630AYoqi58ZM1zdVPNXJUKKNhzTD5/7HmD/zZWgvjPlObMI7OEo9/xk741nn36Cr7bQOqqXGF9rCOPPpVp9GrEylAYzkHU5cCP+f+cnMKR0bs45/Vn7QwfINK1iXRb7UWljXadu/amxg5fJMvEzv+NBSVJ3Qy8UmDo6sMFLMkSngAeZZoupqarLhdWn0xOPW0A5DHt4FzhWTuGgYZU+jC3l1nAjeKGj7NjW8sUpb5cSfmqBxLd79HtfbY4S/IbsYCCkJNfchhv516GUFtmwaeEYZOVpsimkoydW7FzhVzgsTLYhhIuXuY1Hq73xETkPe2N/DuS2OxhJGbRygS6IpLc8tWj5qS5ZyLjHeSohu7jB3+CWmRCLffv57QEF52IpunEGE4E2vTOUI2qFZ47121lhhkLDQ3UBGaFu6jwSPJI87esFNjw5ycLUbUdgv6qlcxDr52owy4="
    # DOCKER_PASSWORD
    - secure: "N3W7Lz1TgbV4gtjrtfxgubsQq4lp52ViI3SdGrHUfkKH5ZXZu5+zE3dyuyOA5dBgSe0/NgB5LUTmr5FfK20yBvSbuFTtMhTOzwdcWbokBCLetm3a4fzCELqqGk3Rxc5ff3V/udvAquy/SoJ3xc1QBt1WCPQ2GRhmHXRMvQiks4xLAVXR39Lq5WwPVzIYxrQU+SVt3TWAf0VCuF8RXoK5xCTps6rmUZsEEelb0W2+khrK0ymLiOeF7fZM4ukerAWWp79mLxlKTbyThAx+2bgHcc+N2r/iGZJS8VLnmWOjr0j60ndpjT1LInQltIPhnB/KXT2oiFjvNuLCKKhFaElWhn8iRAOIpNKdqZniItSV1oJTnJB5fP8Ta3X14sT8cYx/h9b/n9pBQidYNr+p5mZdra0XhSfJdpcR4opiJ+u/bnfFeWPG26U1oGfkxAXjnN50PH4e3KPQmt0n4QXz9jJGgn+QX34QD+zkSYMa/LLRL4QAEv1iUv8uQGES18nZ/vOzOEpw0aZrJHBUXdGDDV4U8SB7JDBALZHY1oxPZihFGJVJbu/hg06OzKIel2N4mixt0IAdwnI7c7QoOx889ebBJh8FJ/vic0xc8b+pm2UOOwF32gndUH8xLWKbDLcWRGRlTwj8a2lzo6SUBwsQUeHD7QSCOYMFqYCYMZhXWuYndmo="
    - IMAGE_NAME=joachimprinzbach/concat-service
    - IMAGE_NAME2=joachimprinzbach/greeting-service

before_install:
  - chmod +x mvnw

script:
  - ./mvnw clean install -B
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - export TAG=$(if [ ! -z "$TRAVIS_TAG" ]; then echo "$TRAVIS_TAG"; else echo "$BRANCH-$TRAVIS_COMMIT"; fi | sed 's/\//-/')
  - docker build concat-service -t $IMAGE_NAME:latest
  - if [ $BRANCH = "master" ]; then docker tag $IMAGE_NAME:latest $IMAGE_NAME:master; fi
  - docker tag $IMAGE_NAME:latest $IMAGE_NAME:$TAG
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker push $IMAGE_NAME:latest
  - if [ $BRANCH = "master" ]; then docker push $IMAGE_NAME:master; fi
  - docker push $IMAGE_NAME:$TAG
  - docker build concat-service -t $IMAGE_NAME2:latest
  - if [ $BRANCH = "master" ]; then docker tag $IMAGE_NAME2:latest $IMAGE_NAME2:master; fi
  - docker tag $IMAGE_NAME2:latest $IMAGE_NAME2:$TAG
  - docker push $IMAGE_NAME2:latest
  - if [ $BRANCH = "master" ]; then docker push $IMAGE_NAME2:master; fi
  - docker push $IMAGE_NAME2:$TAG

cache:
  directories:
    - '$HOME/.m2/repository'